const CONFIG = {
  allAttrs: [
    'width',
    'height',
    'font-weight',
    'font-size',
    'color',
    'line-height',
    'border',
    'border-radius',
    'background',
    'background-color',
    'box-shadow',
    'text-shadow',
  ],
  units: ["px", "rpx", "rem", "pt", "em"],
  scales: [1, 2, 0.5],
  // 初始设置
  settings: [
    {
      id: 0,
      name: 'config',
      enabled: true,
      attrs: [
        'font-weight',
        'font-size',
        'line-height',
        'color',
        'border',
        'border-radius',
        'background',
        'background-color',
        'box-shadow',
        'text-shadow',
      ],
      unit: 'px',
      scale: 1,
      border1pxEnabled: true,
      fixFontWeight: true,
      varEnable: false,
      varStr: '',
    },
    {
      id: 1,
      name: 'config 1',
      enabled: true,
      attrs: [
        'font-weight',
        'font-size',
        'line-height',
        'color',
        'border',
        'border-radius',
        'background',
        'background-color',
        'box-shadow',
        'text-shadow',
      ],
      unit: 'px',
      scale: 1,
      border1pxEnabled: true,
      fixFontWeight: true,
      varEnable: false,
      varStr: '',
    },
  ],
};

export default CONFIG;
